USE [master]
GO

/****** Object:  Database [db_gran_colo]    Script Date: 20/11/2019 18:48:01 ******/
CREATE DATABASE [db_gran_colo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_gran_colo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\db_gran_colo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_gran_colo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\db_gran_colo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_gran_colo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_gran_colo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_gran_colo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_gran_colo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_gran_colo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_gran_colo] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_gran_colo] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [db_gran_colo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_gran_colo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_gran_colo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_gran_colo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_gran_colo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_gran_colo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_gran_colo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_gran_colo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_gran_colo] SET  ENABLE_BROKER 
GO

ALTER DATABASE [db_gran_colo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_gran_colo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_gran_colo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_gran_colo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_gran_colo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_gran_colo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_gran_colo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_gran_colo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_gran_colo] SET  MULTI_USER 
GO

ALTER DATABASE [db_gran_colo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_gran_colo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_gran_colo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_gran_colo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_gran_colo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_gran_colo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [db_gran_colo] SET  READ_WRITE 
GO

